LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := lights.picasso
LOCAL_MODULE_TAGS  := optional

COMMON_MODULE_PATH := $(TARGET_OUT_PRODUCT)/vendor_overlay/$(PRODUCT_TARGET_VNDK_VERSION)
LOCAL_MODULE_PATH_32 := $(COMMON_MODULE_PATH)/lib
LOCAL_MODULE_PATH_64 := $(COMMON_MODULE_PATH)/lib64
LOCAL_MODULE_RELATIVE_PATH := hw
LOCAL_INSTALLED_MODULE_STEM := lights.lito.so

LOCAL_CFLAGS := -DLOG_TAG=\"qdlights\"
LOCAL_CLANG  := true

LOCAL_SRC_FILES := \
    lights.c

LOCAL_SHARED_LIBRARIES := \
    liblog

LOCAL_HEADER_LIBRARIES := \
    libhardware_headers

include $(BUILD_SHARED_LIBRARY)
